export { copy16Filled } from "./copy16Filled";
export { copy16Regular } from "./copy16Regular";
export { copy20Filled } from "./copy20Filled";
export { copy20Regular } from "./copy20Regular";
export { copy24Filled } from "./copy24Filled";
export { copy24Regular } from "./copy24Regular";
export { copy32Filled } from "./copy32Filled";
export { copy32Light } from "./copy32Light";
export { copy32Regular } from "./copy32Regular";
