export { calendarEdit16Filled } from "./calendarEdit16Filled";
export { calendarEdit16Regular } from "./calendarEdit16Regular";
export { calendarEdit20Filled } from "./calendarEdit20Filled";
export { calendarEdit20Regular } from "./calendarEdit20Regular";
export { calendarEdit24Filled } from "./calendarEdit24Filled";
export { calendarEdit24Regular } from "./calendarEdit24Regular";
export { calendarEdit32Filled } from "./calendarEdit32Filled";
export { calendarEdit32Light } from "./calendarEdit32Light";
export { calendarEdit32Regular } from "./calendarEdit32Regular";
