export { breakoutRoom20Filled } from "./breakoutRoom20Filled";
export { breakoutRoom20Regular } from "./breakoutRoom20Regular";
export { breakoutRoom24Filled } from "./breakoutRoom24Filled";
export { breakoutRoom24Regular } from "./breakoutRoom24Regular";
export { breakoutRoom28Filled } from "./breakoutRoom28Filled";
export { breakoutRoom28Regular } from "./breakoutRoom28Regular";
export { breakoutRoom32Filled } from "./breakoutRoom32Filled";
export { breakoutRoom32Light } from "./breakoutRoom32Light";
export { breakoutRoom32Regular } from "./breakoutRoom32Regular";
