export { peopleEdit16Filled } from "./peopleEdit16Filled";
export { peopleEdit16Regular } from "./peopleEdit16Regular";
export { peopleEdit20Filled } from "./peopleEdit20Filled";
export { peopleEdit20Regular } from "./peopleEdit20Regular";
export { peopleEdit24Filled } from "./peopleEdit24Filled";
export { peopleEdit24Regular } from "./peopleEdit24Regular";
export { peopleEdit32Filled } from "./peopleEdit32Filled";
export { peopleEdit32Light } from "./peopleEdit32Light";
export { peopleEdit32Regular } from "./peopleEdit32Regular";
