export { starAdd16Filled } from "./starAdd16Filled";
export { starAdd16Regular } from "./starAdd16Regular";
export { starAdd20Filled } from "./starAdd20Filled";
export { starAdd20Regular } from "./starAdd20Regular";
export { starAdd24Filled } from "./starAdd24Filled";
export { starAdd24Regular } from "./starAdd24Regular";
export { starAdd28Filled } from "./starAdd28Filled";
export { starAdd28Regular } from "./starAdd28Regular";
export { starAdd32Light } from "./starAdd32Light";
