export { clipboardPaste16Filled } from "./clipboardPaste16Filled";
export { clipboardPaste16Regular } from "./clipboardPaste16Regular";
export { clipboardPaste20Filled } from "./clipboardPaste20Filled";
export { clipboardPaste20Regular } from "./clipboardPaste20Regular";
export { clipboardPaste24Filled } from "./clipboardPaste24Filled";
export { clipboardPaste24Regular } from "./clipboardPaste24Regular";
export { clipboardPaste32Filled } from "./clipboardPaste32Filled";
export { clipboardPaste32Light } from "./clipboardPaste32Light";
export { clipboardPaste32Regular } from "./clipboardPaste32Regular";
