export { mailArrowClockwise16Filled } from "./mailArrowClockwise16Filled";
export { mailArrowClockwise16Regular } from "./mailArrowClockwise16Regular";
export { mailArrowClockwise20Filled } from "./mailArrowClockwise20Filled";
export { mailArrowClockwise20Regular } from "./mailArrowClockwise20Regular";
export { mailArrowClockwise24Filled } from "./mailArrowClockwise24Filled";
export { mailArrowClockwise24Regular } from "./mailArrowClockwise24Regular";
export { mailArrowClockwise32Filled } from "./mailArrowClockwise32Filled";
export { mailArrowClockwise32Light } from "./mailArrowClockwise32Light";
export { mailArrowClockwise32Regular } from "./mailArrowClockwise32Regular";
